"""Proposal provenance generated by an optimization session."""

from __future__ import annotations

from dataclasses import dataclass

from genio.core.individual import Individual


@dataclass(frozen=True, slots=True)
class Proposal:
    """Identify one occurrence of an individual proposed during a search run.

    A proposal is distinct from an :class:`Individual`: an algorithm may submit
    the same individual or genotype more than once, but each occurrence receives
    its own monotonic sequence and run-scoped ``proposal_id``.

    Attributes:
        proposal_id: Run-scoped identifier generated by the session.
        proposal_sequence: Zero-based position across all proposals in the run.
        batch_index: Batch containing the proposal, or ``None`` for evaluations
            requested directly through ``OptimizationSession.evaluate``.
        batch_position: Zero-based position within the submitted batch.
        individual: Candidate associated with this proposal occurrence.
    """

    proposal_id: str
    proposal_sequence: int
    batch_index: int | None
    batch_position: int
    individual: Individual

    def evaluation_metadata(self) -> dict[str, int | str | None]:
        """Return proposal provenance suitable for evaluation metadata."""

        return {
            "proposal_id": self.proposal_id,
            "proposal_sequence": self.proposal_sequence,
            "batch_index": self.batch_index,
            "batch_position": self.batch_position,
        }


__all__ = ["Proposal"]
