from __future__ import annotations

import json
from abc import ABC, abstractmethod
from collections.abc import Mapping
from pathlib import Path
from typing import Any, Iterator

from genio.core import Individual, StageChoice
from genio.search_space import SearchSpace


class ComposerError(Exception):
    """Base error for composer failures."""


class StageDefinitionNotFoundError(ComposerError):
    """Raised when an Individual references an unknown stage."""


class ExecutionPackage(ABC):
    """Portable execution payload generated by a composer."""

    @property
    @abstractmethod
    def entrypoint(self) -> str:
        """Return the package entrypoint."""

        raise NotImplementedError

    @property
    @abstractmethod
    def files(self) -> Mapping[str, str]:
        """Return the files contained in the package."""

        raise NotImplementedError

    @abstractmethod
    def materialize(self, target_dir: str | Path) -> Path:
        """Write package files under target_dir and return that directory."""


class Composer(ABC):
    """Base class for backend-specific composers.

    The base composer owns common traversal and definition-loading logic.
    Subclasses decide what execution artifacts to generate for each backend.
    """

    def __init__(self, stages_definitions_path: str | Path) -> None:
        self.stages_definitions_path = Path(stages_definitions_path)
        self.stage_definitions = SearchSpace._load_stage_definitions(
            self.stages_definitions_path
        )

    @abstractmethod
    def compose(self, individual: Individual) -> ExecutionPackage:
        """Generate backend-specific execution artifacts from an Individual."""

    def active_choices(self, individual: Individual) -> Iterator[StageChoice]:
        """Yield the active stage choices for an individual."""

        for choice in individual.slots:
            if not self.should_skip(choice):
                yield choice

    def active_stage_definitions(
        self,
        individual: Individual,
    ) -> Iterator[tuple[StageChoice, dict[str, Any]]]:
        """Yield active stage choices with their definitions."""

        for choice in self.active_choices(individual):
            yield choice, self.stage_definition(choice.stage)

    def should_skip(self, choice: StageChoice) -> bool:
        """Return whether a stage choice should be skipped."""

        return choice.stage == "nop"

    def stage_definition(self, stage: str) -> dict[str, Any]:
        """Return the definition for a stage identifier."""

        try:
            return self.stage_definitions[stage]
        except KeyError as exc:
            raise StageDefinitionNotFoundError(
                f"Stage {stage!r} is not defined in {self.stages_definitions_path}."
            ) from exc

    def artifact_metadata(self, individual: Individual) -> dict[str, Any]:
        """Build common artifact metadata for an individual."""

        return {
            "composer": self.__class__.__name__,
            "scenario": individual.scenario,
            "search_index": individual.search_index,
        }
