from __future__ import annotations

import json
import hashlib
from abc import ABC, abstractmethod
from collections.abc import Mapping
from pathlib import Path
from typing import Any, Iterator

from genio.core import Individual, StageChoice
from genio.search_space import SearchSpace


class ComposerError(Exception):
    """Base error for composer failures."""


class StageDefinitionNotFoundError(ComposerError):
    """Raised when an Individual references an unknown stage."""


class ExecutionPackage(ABC):
    """Portable execution payload generated by a composer."""

    @property
    @abstractmethod
    def entrypoint(self) -> str:
        """Return the package entrypoint."""

        raise NotImplementedError

    @property
    @abstractmethod
    def files(self) -> Mapping[str, str]:
        """Return the files contained in the package."""

        raise NotImplementedError

    @abstractmethod
    def materialize(self, target_dir: str | Path) -> Path:
        """Write package files under target_dir and return that directory."""


class Composer(ABC):
    """Base class for backend-specific composers.

    The base composer owns common traversal and definition-loading logic.
    Subclasses decide what execution artifacts to generate for each backend.
    """

    def __init__(self, stages_definitions_path: str | Path) -> None:
        self.stages_definitions_path = Path(stages_definitions_path)
        self.stage_definitions = SearchSpace._load_stage_definitions(
            self.stages_definitions_path
        )

    @abstractmethod
    def compose(self, individual: Individual) -> ExecutionPackage:
        """Generate backend-specific execution artifacts from an Individual."""

    def active_choices(self, individual: Individual) -> Iterator[StageChoice]:
        """Yield the active stage choices for an individual."""

        for choice in individual.slots:
            if not self.should_skip(choice):
                yield choice

    def active_stage_definitions(
        self,
        individual: Individual,
    ) -> Iterator[tuple[StageChoice, dict[str, Any]]]:
        """Yield active stage choices with their definitions."""

        for choice in self.active_choices(individual):
            yield choice, self.stage_definition(choice.stage)

    def should_skip(self, choice: StageChoice) -> bool:
        """Return whether a stage choice should be skipped."""

        return choice.stage == "nop"

    def stage_definition(self, stage: str) -> dict[str, Any]:
        """Return the definition for a stage identifier."""

        try:
            return self.stage_definitions[stage]
        except KeyError as exc:
            raise StageDefinitionNotFoundError(
                f"Stage {stage!r} is not defined in {self.stages_definitions_path}."
            ) from exc

    def artifact_metadata(self, individual: Individual) -> dict[str, Any]:
        """Build common artifact metadata for an individual."""

        return {
            "composer": self.__class__.__name__,
            "scenario": individual.scenario,
            "search_index": individual.search_index,
        }

    def checkpoint_signature(self) -> Mapping[str, Any]:
        """Return definition files that determine generated package semantics."""

        definition_files = {
            item.resolve()
            for item in self.stages_definitions_path.rglob("*")
            if item.is_file()
        }
        for definition in self.stage_definitions.values():
            for relative_path in self._implementation_paths(
                definition.get("implementations", {})
            ):
                implementation = (
                    self.stages_definitions_path.parent / relative_path
                ).resolve()
                if implementation.is_file():
                    definition_files.add(implementation)
        return {
            "type": f"{type(self).__module__}.{type(self).__qualname__}",
            "stages_definitions_path": str(
                self.stages_definitions_path.expanduser().resolve()
            ),
            "definition_files": self._file_fingerprints(
                definition_files,
                relative_to=self.stages_definitions_path.parent,
            ),
        }

    @staticmethod
    def _directory_fingerprint(path: Path) -> list[dict[str, str]]:
        root = path.expanduser().resolve()
        return Composer._file_fingerprints(
            (item for item in root.rglob("*") if item.is_file()),
            relative_to=root,
        )

    @staticmethod
    def _file_fingerprints(
        files: Iterator[Path] | set[Path],
        *,
        relative_to: Path,
    ) -> list[dict[str, str]]:
        root = relative_to.expanduser().resolve()
        return [
            {
                "path": file.relative_to(root).as_posix(),
                "sha256": hashlib.sha256(file.read_bytes()).hexdigest(),
            }
            for file in sorted(Path(item).resolve() for item in files)
        ]

    @classmethod
    def _implementation_paths(cls, value: Any) -> Iterator[str]:
        if isinstance(value, str):
            yield value
        elif isinstance(value, Mapping):
            for item in value.values():
                yield from cls._implementation_paths(item)
        elif isinstance(value, (list, tuple)):
            for item in value:
                yield from cls._implementation_paths(item)
