#ifndef GENIO_APP_CONFIG_H_
#define GENIO_APP_CONFIG_H_

#define GENIO_INPUT_ROWS @INPUT_ROWS@
#define GENIO_INPUT_COLS @INPUT_COLS@
#define GENIO_OUTPUT_ROWS @OUTPUT_ROWS@
#define GENIO_OUTPUT_COLS @OUTPUT_COLS@

#define GENIO_INPUT_WORDS @INPUT_WORDS@
#define GENIO_OUTPUT_WORDS @OUTPUT_WORDS@

#define GENIO_DMA_CHANNEL @DMA_CHANNEL@
#define GENIO_TIMEOUT_CYCLES @TIMEOUT_CYCLES@

#endif
