from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Sequence

from genio.artifacts.base import Artifact, MetricArtifact


@dataclass(frozen=True, slots=True)
class HLSReportArtifact(MetricArtifact):
    """Parsed HLS-related reports with metrics scoped by their origin."""

    origin: str
    report_paths: tuple[Path, ...] = ()
    values: Mapping[str, float] = field(default_factory=dict)

    def load(self) -> Sequence[Any]:
        return (self.report_paths, self.values)

    def metrics(self) -> Mapping[str, float]:
        return {f"{self.origin}.{key}": value for key, value in self.values.items()}


@dataclass(frozen=True, slots=True)
class HLSRTLArtifact(Artifact):
    """RTL files generated by one stage of an HLS toolchain."""

    origin: str
    top_function: str
    verilog_paths: tuple[Path, ...] = ()
    vhdl_paths: tuple[Path, ...] = ()

    @property
    def rtl_paths(self) -> tuple[Path, ...]:
        return self.verilog_paths + self.vhdl_paths

    def load(self) -> Sequence[Any]:
        return self.rtl_paths


__all__ = [
    "HLSReportArtifact",
    "HLSRTLArtifact",
]
