"""Public API for building and running GENIO optimization searches.

GENIO separates candidate generation, evaluation, execution, and observation.
A typical application creates a :class:`SearchSpace`, selects a
:class:`SearchAlgorithm`, combines one or more :class:`EvaluationStep` objects
in an :class:`EvaluationWorkflow`, and passes those components to an
:class:`OptimizationSession`.

The names re-exported here form the supported convenience API. Subpackages can
still be imported directly when implementing custom algorithms, evaluators,
backends, composers, artifacts, or statistics collectors.
"""

from genio.algorithm import (
    GeneticSearch,
    GridSearch,
    NSGA2Search,
    RandomSearch,
    SearchAlgorithm,
    SearchContext,
)
from genio.artifacts import (
    Artifact,
    ArtifactError,
    HLSReportArtifact,
    HLSRTLArtifact,
    ImageFunctionalMetricsArtifact,
    MetricArtifact,
    XHeepSimulationArtifact,
)
from genio.backend import (
    Backend,
    BackendError,
    BackendShutdownError,
    EvaluationHandle,
    EvaluationState,
    LocalBackend,
    ParallelLocalBackend,
    ParallelSSHBackend,
    SSHBackend,
    UnknownEvaluationHandleError,
)
from genio.cache import ArtifactCache, CacheEntry, LFUArtifactCache
from genio.checkpoint import (
    CheckpointCompatibilityError,
    CheckpointError,
    CheckpointFormatError,
    CheckpointNotSupportedError,
    CheckpointPolicy,
    CheckpointStateError,
    JSONCheckpointStore,
)
from genio.composer import (
    Composer,
    ComposerError,
    ExecutionPackage,
    GRHeepConfigurationComposer,
    GRHeepConfigurationPackage,
    HLSExecutionPackage,
    HLSImagePipelineComposer,
    PythonExecutionPackage,
    PythonImagePipelineComposer,
    StageDefinitionNotFoundError,
)
from genio.core import (
    Evaluation,
    Individual,
    Proposal,
    Result,
    ResultStatus,
    SearchResult,
    StageChoice,
)
from genio.evaluation import (
    CommandResult,
    EvaluationExecutionError,
    EvaluationExecutor,
    EvaluationStep,
    EvaluationTask,
    EvaluationWorkflow,
    EvaluationWorkflowError,
    ExecutionContext,
    HLSImagePipelineSynthesisConfigurationError,
    HLSImagePipelineSynthesisError,
    HLSImagePipelineSynthesisTimeoutError,
    HLSImagePipelineSynthesisEvaluationStep,
    HLSImagePipelineSynthesisTask,
    ImageFunctionalQualityError,
    PythonImageFunctionalEvaluationStep,
    PythonImageFunctionalTask,
    XHeepVerilatorSimulationConfigurationError,
    XHeepVerilatorSimulationError,
    XHeepVerilatorSimulationEvaluationStep,
    XHeepVerilatorSimulationResultError,
    XHeepVerilatorSimulationTask,
    XHeepVerilatorSimulationTimeoutError,
)
from genio.objective import (
    IdentityScalarizer,
    MetricObjective,
    MinMaxNormalizer,
    NormalizationScope,
    Objective,
    ObjectiveError,
    ObjectiveSet,
    OptimizationDirection,
    WeightedMeanScalarizer,
)
from genio.search_space import SearchScenarioSpec, SearchSpace, SlotSpec
from genio.session import OptimizationSession
from genio.statistics import CSVStatisticsCollector, InMemoryStatistics, StatisticsCollector

__all__ = [
    "Backend",
    "BackendError",
    "BackendShutdownError",
    "Artifact",
    "ArtifactCache",
    "ArtifactError",
    "Composer",
    "ComposerError",
    "CSVStatisticsCollector",
    "CacheEntry",
    "CheckpointCompatibilityError",
    "CheckpointError",
    "CheckpointFormatError",
    "CheckpointNotSupportedError",
    "CheckpointPolicy",
    "CheckpointStateError",
    "CommandResult",
    "Evaluation",
    "EvaluationExecutionError",
    "EvaluationExecutor",
    "EvaluationHandle",
    "EvaluationState",
    "EvaluationStep",
    "EvaluationTask",
    "EvaluationWorkflow",
    "EvaluationWorkflowError",
    "ExecutionPackage",
    "ExecutionContext",
    "GeneticSearch",
    "GridSearch",
    "GRHeepConfigurationComposer",
    "GRHeepConfigurationPackage",
    "HLSImagePipelineSynthesisConfigurationError",
    "HLSImagePipelineSynthesisError",
    "HLSImagePipelineSynthesisTimeoutError",
    "HLSImagePipelineSynthesisEvaluationStep",
    "HLSImagePipelineSynthesisTask",
    "HLSReportArtifact",
    "HLSRTLArtifact",
    "HLSExecutionPackage",
    "HLSImagePipelineComposer",
    "ImageFunctionalQualityError",
    "ImageFunctionalMetricsArtifact",
    "IdentityScalarizer",
    "InMemoryStatistics",
    "Individual",
    "JSONCheckpointStore",
    "LocalBackend",
    "LFUArtifactCache",
    "MetricArtifact",
    "MetricObjective",
    "MinMaxNormalizer",
    "NSGA2Search",
    "NormalizationScope",
    "Objective",
    "ObjectiveError",
    "ObjectiveSet",
    "OptimizationSession",
    "OptimizationDirection",
    "ParallelLocalBackend",
    "ParallelSSHBackend",
    "Proposal",
    "PythonExecutionPackage",
    "PythonImagePipelineComposer",
    "PythonImageFunctionalEvaluationStep",
    "PythonImageFunctionalTask",
    "Result",
    "ResultStatus",
    "RandomSearch",
    "SearchAlgorithm",
    "SearchContext",
    "SearchScenarioSpec",
    "SearchSpace",
    "SearchResult",
    "SSHBackend",
    "SlotSpec",
    "StatisticsCollector",
    "StageDefinitionNotFoundError",
    "StageChoice",
    "UnknownEvaluationHandleError",
    "XHeepSimulationArtifact",
    "XHeepVerilatorSimulationConfigurationError",
    "XHeepVerilatorSimulationError",
    "XHeepVerilatorSimulationEvaluationStep",
    "XHeepVerilatorSimulationResultError",
    "XHeepVerilatorSimulationTask",
    "XHeepVerilatorSimulationTimeoutError",
    "WeightedMeanScalarizer",
]
